---
title: Registry (personal)
description: Personal registry configuration
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Tweaking registry'}

    # ======> Taskbar
    # === Never combine taskbar buttons - On
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarGlomLevel', type: REG_DWORD, data: '2'}
    # === Small taskbar buttons - On
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarSi', type: REG_DWORD, data: '0'}
    # Disable Cloud Optimized Content on Taskbar
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\CloudContent', value: 'DisableCloudOptimizedContent', data: '1', type: REG_DWORD}
    # Disable Show Desktop Peek on Taskbar
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'DisablePreviewDesktop', data: '1', type: REG_DWORD}
    # Disable Task View on Taskbar
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\MultiTaskingView\AllUpView', value: 'Enabled', operation: delete}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowTaskViewButton', data: '0', type: REG_DWORD}
    # Set Taskbar to Align Left
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarAl', data: '0', type: REG_DWORD}
    # Disable Search button
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Search', value: 'SearchboxTaskbarMode', type: REG_DWORD, data: '0'}

    # ======> File associations
  - !registryValue: {path: 'HKCU\Software\Classes\.ps1', value: '', type: REG_SZ, data: 'Microsoft.PowerShellScript.1'}
    # === Firefox
  - !registryValue: {path: 'HKCU\Software\Classes\https', value: '', type: REG_SZ, data: 'FirefoxURL-308046B0AF4A39CB', option: 'browser-firefox'}
  - !registryValue: {path: 'HKCU\Software\Classes\http', value: '', type: REG_SZ, data: 'FirefoxURL-308046B0AF4A39CB', option: 'browser-firefox'}
  - !registryValue: {path: 'HKCU\Software\Classes\.htm', value: '', type: REG_SZ, data: 'FirefoxURL-308046B0AF4A39CB', option: 'browser-firefox'}
  - !registryValue: {path: 'HKCU\Software\Classes\.html', value: '', type: REG_SZ, data: 'FirefoxURL-308046B0AF4A39CB', option: 'browser-firefox'}
  - !registryValue: {path: 'HKCU\Software\Classes\.shtml', value: '', type: REG_SZ, data: 'FirefoxURL-308046B0AF4A39CB', option: 'browser-firefox'}
    # === Brave
  - !registryValue: {path: 'HKCU\Software\Classes\https', value: '', type: REG_SZ, data: 'BraveHTML', option: 'browser-brave'}
  - !registryValue: {path: 'HKCU\Software\Classes\http', value: '', type: REG_SZ, data: 'BraveHTML', option: 'browser-brave'}
  - !registryValue: {path: 'HKCU\Software\Classes\.htm', value: '', type: REG_SZ, data: 'BraveHTML', option: 'browser-brave'}
  - !registryValue: {path: 'HKCU\Software\Classes\.html', value: '', type: REG_SZ, data: 'BraveHTML', option: 'browser-brave'}
  - !registryValue: {path: 'HKCU\Software\Classes\.shtml', value: '', type: REG_SZ, data: 'BraveHTML', option: 'browser-brave'}

    # ======> Explorer
    # === Compact mode - On
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'UseCompactMode', type: REG_DWORD, data: '1'}
    # === Disable Gallery - On
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}', value: 'System.IsPinnedToNameSpaceTree', type: REG_DWORD, data: '0'}
    # === Disable Shortcut Text - On
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\NamingTemplates', value: 'ShortcutNameTemplate', type: REG_SZ, data: '"%s.lnk"'}
    # === Disable News and Interests - On
  - !registryValue: {path: 'HKCU\Software\Microsoft\PolicyManager\default\NewsAndInterests\AllowNewsAndInterests', value: 'value', type: REG_DWORD, data: '0'}
    # Disables full drive indexing (Enhanced Search)
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows Search\Gather\Windows\SystemIndex', value: 'EnableFindMyFiles', type: REG_DWORD, data: '0'}
    # Revert to Classic Search
  - !registryValue: {path: 'HKLM\Software\Classes\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs', value: '', data: '{64bc32b5-4eec-4de7-972d-bd8bd0324537}', type: REG_SZ}
  - !registryValue: {path: 'HKLM\Software\Classes\WOW6432Node\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs', value: '', data: '{64bc32b5-4eec-4de7-972d-bd8bd0324537}', type: REG_SZ}
  - !registryValue: {path: 'HKLM\Software\WOW6432Node\Classes\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs', value: '', data: '{64bc32b5-4eec-4de7-972d-bd8bd0324537}', type: REG_SZ}

    # ======> Security
    # === UAC
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ConsentPromptBehaviorAdmin', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ConsentPromptBehaviorUser', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableInstallerDetection', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableLUA', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableSecureUIAPaths', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableVirtualization', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'PromptOnSecureDesktop', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ValidateAdminCodeSignatures', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'FilterAdministratorToken', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableUIADesktopToggle', type: REG_DWORD, data: '0'}

    # === HVCI - Off
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\DeviceGuard', value: 'EnableVirtualizationBasedSecurity', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\DeviceGuard', value: 'RequirePlatformSecurityFeatures', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\DeviceGuard', value: 'Locked', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity', value: 'Enabled', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity', value: 'Locked', data: '0', type: REG_DWORD}

    # Blocks Anonymous Enumeration of SAM Accounts
    # https://www.stigviewer.com/stig/microsoft_windows_10/2022-04-08/finding/V-220929
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\Lsa', value: 'RestrictAnonymousSAM', data: '1', type: REG_DWORD}

    # Disable Remote Assistance
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\Remote Assistance', value: 'fAllowFullControl', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\Remote Assistance', value: 'fAllowToGetHelp', data: '0', type: REG_DWORD}

    # ======> Locale
    # === Set Central Europe Time - On
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\TimeZoneInformation', value: 'TimeZoneKeyName', type: REG_SZ, data: 'Romance Standard Time'}
    # === European formats
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'iCalendarType', type: REG_SZ, data: '1'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'iDate', type: REG_SZ, data: '1'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'iFirstDayOfWeek', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'iFirstWeekOfYear', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'iLZero', type: REG_SZ, data: '1'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sCurrency', type: REG_SZ, data: '€'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sDate', type: REG_SZ, data: '/'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sDecimal', type: REG_SZ, data: '.'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sGrouping', type: REG_SZ, data: '3;0'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sList', type: REG_SZ, data: ','}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sShortDate', type: REG_SZ, data: 'dd/MM/yyyy'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sShortTime', type: REG_SZ, data: 'HH:mm'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sThousand', type: REG_SZ, data: ','}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sTime', type: REG_SZ, data: ':'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sTimeFormat', type: REG_SZ, data: 'HH:mm:ss'}
  - !registryValue: {path: 'HKCU\Control Panel\International', value: 'sYearMonth', type: REG_SZ, data: 'MMMM yyyy'}

    # ======> Extra
    # === Disable MPO - On
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\Dwm', value: 'OverlayTestMode', type: REG_DWORD, data: '5'}

    # ======> Configure Storage Sense
    # Reference: https://gist.github.com/he3als/3d9dcf6e796aa920c24a98130165fb17

    # Enable Storage Sense
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '01', type: REG_DWORD, data: '1'}
    # Run Storage Sense
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '1024', type: REG_DWORD, data: '1'}
    # Run Storage Sense every month
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '2048', type: REG_DWORD, data: '30'}
    # Enable cleaning temporary files
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '04', type: REG_DWORD, data: '1'}
    # Disable the 'Downloads' from being cleared
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '32', type: REG_DWORD, data: '0'}
    # Disable OneDrive cleanup
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '02', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '128', type: REG_DWORD, data: '0'}
    # Clean Recycle Bin every month
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '08', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '256', type: REG_DWORD, data: '30'}
    # Enable cleaning temp files
  - !scheduledTask: {path: '\Microsoft\Windows\DiskCleanup\SilentCleanup', operation: enable}

    # ======> Configure Time Servers
    # https://www.pool.ntp.org/en/use.html
  - !service: {name: 'w32time', operation: start, ignoreErrors: true}
  - !run: {exe: 'w32tm', args: '/config /syncfromflags:manual /manualpeerlist:"0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org"'}
  - !run: {exe: 'w32tm', args: '/config /update'}
  - !run: {exe: 'w32tm', args: '/resync'}

    # Disable 'Always Read and Scan This Section'
  - !registryValue: {path: 'HKCU\Software\Microsoft\Ease of Access', value: 'selfscan', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Ease of Access', value: 'selfvoice', data: '0', type: REG_DWORD}

    # Disable Ease of Access Sounds
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility', value: 'Warning Sounds', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility', value: 'Sound on Activation', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\SoundSentry', value: 'WindowsEffect', data: '0', type: REG_SZ}

    # Do Not Show Edge Tabs in Alt-Tab
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'MultiTaskingAltTabFilter', data: '3', type: REG_DWORD}

    # Disable AutoRun/AutoPlay
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoAutorun', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers', value: 'DisableAutoplay', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoDriveTypeAutoRun', data: '255', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoAutorun', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\Explorer', value: 'NoAutoplayfornonVolume', data: '1', type: REG_DWORD}

    # Disable Recommendations in the Start Menu
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'Start_IrisRecommendations', data: '0', type: REG_DWORD, builds: ['>=22000']}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'Start_AccountNotifications', data: '0', type: REG_DWORD}

    # Configure Visual Effects
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'FontSmoothing', data: '2', type: REG_SZ}
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'UserPreferencesMask', data: '9012038010000000', type: REG_BINARY}
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'DragFullWindows', data: '1', type: REG_SZ}
  - !registryValue: {path: 'HKCU\Control Panel\Desktop\WindowMetrics', value: 'MinAnimate', data: '0', type: REG_SZ}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ListviewAlphaSelect', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'IconsOnly', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarAnimations', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ListviewShadow', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects', value: 'VisualFXSetting', data: '3', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\DWM', value: 'EnableAeroPeek', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\DWM', value: 'AlwaysHibernateThumbnails', data: '0', type: REG_DWORD}

    # Disable Recycle Bin shortcut on Desktop
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\NonEnum', value: '{645FF040-5081-101B-9F08-00AA002F954E}', data: '1', type: REG_DWORD}

    # Skip swipe screen in lock screen
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\Personalization', value: 'NoLockScreen', data: '1', type: REG_DWORD}

    # Configure BitLocker to only use PCR 11
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: 'Enabled', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: '0', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: '2', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: '4', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: '7', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE\OSPlatformValidation_UEFI', value: '11', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\FVE', value: 'OSAllowSecureBootForIntegrity', data: '0', type: REG_DWORD}

    # Don't do anything when the lid is closed
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Power\PowerSettings\5CA83367-6E45-459F-A27B-476B1D01C936', value: 'ACSettingIndex', data: '0', type: REG_DWORD}

    # Disable Notifications
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications', value: 'NoToastApplicationNotification', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings', value: 'NOC_GLOBAL_SETTING_ALLOW_NOTIFICATION_SOUND', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings', value: 'NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings', value: 'NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings', value: 'NOC_GLOBAL_SETTING_TOASTS_ENABLED', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener', value: 'Value', data: 'Deny', type: REG_SZ}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\Explorer', value: 'ToastEnabled', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\Explorer', value: 'ToastEnabled', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\PushNotifications', value: 'ToastEnabled', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\PushNotifications', value: 'ToastEnabled', data: '0', type: REG_DWORD}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications', value: 'NoCloudApplicationNotification', data: '1', type: REG_DWORD}
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications', value: 'NoCloudApplicationNotification', data: '1', type: REG_DWORD}

    # Disable Caps Lock
  - !registryValue: {path: 'HKLM\System\CurrentControlSet\Control\Keyboard Layout', value: 'Scancode Map', data: '00000000000000000200000000003A0000000000', type: REG_BINARY}

    # Disable screen edge swipe
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\EdgeUI', value: 'AllowEdgeSwipe', data: '0', type: REG_DWORD}

    # Enable windowed games optimizations
  - !registryValue: {path: 'HKCU\Software\Microsoft\DirectX\UserGpuPreferences', value: 'DirectXUserGlobalSettings', data: 'SwapEffectUpgradeEnable=1;', type: REG_SZ}
