name: Archive and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  SXSC_REPO: 'https://github.com/Atlas-OS/sxsc'
  FILENAME: 'Windows-PB-${{ github.ref_name }}.apbx'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive content
        run: |
          7z a -pmalte -mhe=on ${{ env.FILENAME }} ./src/*

      - name: Generate SHA256
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 -Path ${{ env.FILENAME }}).Hash
          echo ("HASH=" + $hash) >> $env:GITHUB_ENV

      # - name: DevUploads
      #   run: |
      #     url=$(bash <(curl -s https://devuploads.com/upload.sh) -f "${{ env.FILENAME }}" -k "${{ secrets.DEVUPLOADS_API_KEY }}" | grep -o 'https://devuploads.com[^"]*')
      #     echo "DEVUPLOADS=$url" >> $GITHUB_ENV

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          release_name: Playbook
          overwrite: true
